auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            Ted
url:              http://wufawei.github.com
feed:             /atom.xml
author:
    name:         Ted
    twitter:      twitter.com/wufawei
description:      "Ted\'s Blog"
author_info:      <a href="http://wufawei.github.com/about">Ted</a>

copyright:
    - Design by <a href="http://wufawei.github.com/about" title="Ted" target="_blank">Ted</a> &copy; 2013
